# Generated by Django 3.2.12 on 2023-04-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230417_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'PropertyType', 'verbose_name_plural': 'PropertyTypes'},
        ),
    ]
