# Generated by Django 3.2.12 on 2023-04-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_propertytype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.AddField(
            model_name='propertytype',
            name='property',
            field=models.OneToOneField(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.property'),
        ),
    ]
